import type { GridState } from '../types';

export function makeGridState(overrides: Partial<GridState> = {}): GridState {
    return {
        projectName: 'Romania Hybrid Solar + BESS',
        projectLocation: 'Romania',
        solarDcCapacityMwp: 117,
        solarAcCapacityMw: 102,
        batteryPowerRatingMw: 188,
        batteryEnergyCapacityMwh: 744,
        gridPvEvacuationMw: 102,
        gridBessConnectionMw: 186,
        siteYieldKwhPerKwYear: 1380,
        simulationStatus: 'running',
        gridFrequencyHz: 50,
        solarOutputMw: 45,
        gridDemandMw: 152,
        dispatchScalePercent: 100,
        batterySocPercent: 65,
        batteryPowerMw: 0,
        batteryChargeFromSolarMw: 0,
        batteryChargeFromGridMw: 0,
        batteryDischargeToGridMw: 0,
        solarExportMw: 45,
        solarCurtailedMw: 0,
        projectNetExportMw: 45,
        batteryMode: 'idle',
        timeOfDay: 8.5,
        timeSpeed: 240,
        timestamp: 0,
        tariffPeriod: 'mid-peak',
        tariffRatesEurMwh: {
            'off-peak': 80,
            'mid-peak': 150,
            'peak': 350,
        },
        currentPriceEurMwh: 150,
        cumulativeRevenueEur: 12340,
        cumulativeBessMarginEur: 2100,
        autoArbEnabled: false,
        ...overrides,
    };
}
